name: Trigger auto deployment for actions-bot

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/actions-bot-AutoDeployTrigger-a1c33e0f-e39a-41db-9bab-b79b4c83f17a.yml'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACTIONSBOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACTIONSBOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACTIONSBOT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: osstooling.azurecr.io
          registryUsername: ${{ secrets.ACTIONSBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACTIONSBOT_REGISTRY_PASSWORD }}
          containerAppName: actions-bot
          resourceGroup: actions-bot
          imageToBuild: osstooling.azurecr.io/actions-bot:${{ github.sha }}
