# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: CI

on:
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
